# Generated by Django 4.1.2 on 2022-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email_send',
            field=models.BooleanField(default=False, verbose_name='Статус отправки email'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='email_status',
            field=models.BooleanField(default=False, verbose_name='Статус доставки email'),
        ),
        migrations.AlterField(
            model_name='userform',
            name='pd_argeement',
            field=models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
