# Generated by Django 4.1.2 on 2023-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('timelines', models.CharField(choices=[('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('10:00 - 18:00', '10:00 - 18:00')], default='11:00 - 12:00', max_length=20)),
                ('weekdays', models.CharField(choices=[('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье'), ('Без экскурсии', 'Без экскурсии')], default='Суббота', max_length=20)),
                ('number_of_visitors', models.IntegerField(default=0)),
                ('total_visitors', models.IntegerField(default=15)),
                ('is_available', models.BooleanField(default=True)),
                ('is_shown', models.BooleanField(default=True)),
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False, verbose_name='id')),
            ],
        ),
    ]
