# Generated by Django 4.1.2 on 2022-10-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_alter_excursion_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='end_datetime',
            field=models.DateTimeField(choices=[('Суббота', '11:00 - 12:00'), ('Воскресенье', '12:00 - 13:00'), ('Без экскурсии', '13:00 - 14:00')]),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='start_datetime',
            field=models.DateTimeField(choices=[('Суббота', '11:00 - 12:00'), ('Воскресенье', '12:00 - 13:00'), ('Без экскурсии', '13:00 - 14:00')]),
        ),
    ]
