# Generated by Django 4.1.2 on 2022-10-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_alter_excursion_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='timelines',
            field=models.TextField(choices=[('11:00 - 12:00', '11:00 - 12:00'), ('12:00 - 13:00', '12:00 - 13:00'), ('13:00 - 14:00', '13:00 - 14:00'), ('14:00 - 15:00', '14:00 - 15:00'), ('16:00 - 17:00', '16:00 - 17:00'), ('17:00 - 18:00', '17:00 - 18:00'), ('10:00 - 18:00', '10:00 - 18:00')], default=('11:00 - 12:00', '11:00 - 12:00')),
        ),
        migrations.AddField(
            model_name='excursion',
            name='weekdays',
            field=models.TextField(choices=[('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье'), ('Без экскурсии', 'Без экскурсии')], default=('Суббота', 'Суббота')),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='end_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
