# Generated by Django 4.1.2 on 2022-11-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0005_remove_excursion_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
