# Generated by Django 4.1.2 on 2022-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0007_alter_excursion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='title',
            field=models.CharField(auto_created=True, default='', max_length=50),
        ),
    ]
