# Generated by Django 4.1.2 on 2022-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0008_alter_excursion_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='title',
        ),
    ]
