# Generated by Django 3.0.2 on 2023-01-01 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_password_link_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
