# Generated by Django 2.2 on 2022-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20220628_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
