# Generated by Django 4.1.5 on 2023-01-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
