# Generated by Django 3.0.2 on 2022-09-07 14:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Cooking', 'Cooking'), ('Lifestyle', 'Lifestyle'), ('Health', 'Health'), ('Productivity', 'Productivity'), ('Beauty', 'Beauty'), ('Other', 'Other')], default='Other', max_length=15)),
                ('text_slug', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.CharField(blank=True, default='', max_length=160)),
                ('image', models.ImageField(upload_to='blog_images/%Y/%m/%d', verbose_name='Blog image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Collects profile ids as integer', size=None)),
                ('is_published', models.BooleanField(blank=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
